name: nightwatch testing-library plugin
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: mkdir -p screens logs
      - run: npm test

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Screenshots
          path: screens/
          retention-days: 1

      - name: Display structure of downloaded files
        if: always()
        run: ls -R
        working-directory: screens/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Logs
          path: logs/
          retention-days: 1

      - name: Display structure of log files
        if: always()
        run: ls -R
        working-directory: logs/
#  release:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#      - uses: actions/checkout@v1
#      - run: npm install
#      - run: npm run build
#      - run: ls -asl dist
#      - run: npx semantic-release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
