name: nightwatch testing-library plugin
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x, 18.x ]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test


#  release:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#      - uses: actions/checkout@v1
#      - run: npm install
#      - run: npm run build
#      - run: ls -asl dist
#      - run: npx semantic-release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
